FROM quay.io/almalinuxorg/9-minimal:${release}

RUN sed -i /etc/yum.repos.d/almalinux*.repo \
      -e 's/^# baseurl=/baseurl=/' \
      -e 's/^mirrorlist=/#mirrorlist=/' \
      -e 's/\$releasever/${release}/' \
    && microdnf clean all

RUN microdnf install -y dnf \
    && dnf remove -y microdnf

ADD https://raw.githubusercontent.com/TurboVNC/repo/main/TurboVNC.repo /etc/yum.repos.d/TurboVNC.repo

RUN dnf update -y \
    && dnf install -y --allowerasing @core \
    && dnf install -y --allowerasing \
      dhclient \
      initscripts \
      ipmitool \
      kernel-core \
      kernel-modules \
      net-tools \
      nfs-utils \
      pciutils \
      rsync \
      strace \
      sudo \
      wget \
      words \
    && dnf install -y epel-release elrepo-release \
    && dnf install -y --allowerasing \
		acl almalinux-release at attr bc cpio crontabs cyrus-sasl-plain \
	    dbus ed file irqbalance kpatch kpatch-dnf logrotate lsof mcelog \
	    microcode_ctl net-tools pciutils psacct quota sudo symlinks \
	    systemd-udev tar tree tuned util-linux-user bash-completion \
	    bluez bpftool bzip2 chrony cockpit cryptsetup dos2unix \
	    dosfstools ethtool gnupg2 iprutils kmod-kvdo ledmon lvm2 \
	    mailcap man-pages mdadm mlocate mtr nano nvme-cli realmd rsync \
	    smartmontools sos sssd strace teamd time unzip usbutils vdo \
	    virt-what which words xfsdump zip cifs-utils cockpit-doc fwupd \
	    ima-evm-utils nfs-utils nvmetcli traceroute vdo-support zsh \
	    glibc-all-langpacks \
	    NetworkManager NetworkManager-tui device-mapper dnf kernel-core \
	    nfs-utils openssh openssh-clients openssh-server sudo less \
	    dnf-plugins-core nano bat wget \
	    autoconf automake binutils bison flex gcc gcc-c++ gdb \
        glibc-devel libtool make pkgconf pkgconf-m4 pkgconf-pkg-config \
        redhat-rpm-config rpm-build rpm-sign strace asciidoc byacc \
        diffstat git intltool jna ltrace patchutils perl-Fedora-VSP \
        perl-generators pesign source-highlight systemtap valgrind \
        valgrind-devel \
        ibacm infiniband-diags iwpmd kmod-mlx4 libibumad libibverbs \
        libibverbs-utils librdmacm librdmacm-utils libvma mstflint \
        opensm perftest rdma-core srp_daemon \
        ipa-client \
        lua lua-posix lua-term tcl \
        munge slurm slurm-slurmd slurm-perlapi \
        nmap-ncat turbovnc python3-websockify xfce4-session xfwm4 \
        xfdesktop libGL xfce4-settings \
    && dnf remove -y selinux-policy \
    && dnf clean all

RUN chmod u+w / # https://github.com/openhpc/ohpc/issues/2061

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
